### ISSUE TITLE
[Question] How I import images or fonts??

### ISSUE THREAD

**Issue by JaeWangL** [hiroppy/ssr-sample#1]
I added image using

>             {
>                 test: /\.(jpe?g|png|gif)$/i,
>                 loader: 'url-loader?limit=1000&name=images/[hash].[ext]'
>             }

```
declare module '*.png' {
    const value: any;
    export = value;
}

import * as test from '../../assets/test.png';
<img src={test} />
```

But I had error 
**Invalid or unexpected token**
**function (exports, require, module, __filename, __dirname) { .PNG**

How I fix this??

----------------------------

Your boilerplate is awesome and best!!

**Comment by hiroppy** [comment]
Did you add `.png` to your `resolve` in your webpack config?

**Comment by JaeWangL** [comment]
@hiroppy  Oh my goodness, I had mistakes. sorry guys.
Thanks your reply!!
and
Your boilerplate is awesome. so, I expect this repo's enhancement

**Comment by hiroppy** [comment]
@JaeWangL Thanks! I will continue to update this repository😉
