### ISSUE TITLE
Could we use absolute path on project?

### ISSUE THREAD

**Issue by wenisy** [hiroppy/ssr-sample#173]
I found we use relative path currently, like below

![image](https://user-images.githubusercontent.com/5832130/64394923-07b75e00-d08b-11e9-9282-878453afd719.png)

But TypeScript support absolute path if we change `baseURL`, `rootDir` and `path`
```
    "rootDir": "src",

    "baseUrl": ".",

    "paths": {
      "*": [
        "src/*"
      ]
    }
```

It would like
```javascript
import { createClient } from 'graphql/client';

import { renderFullPage } from '../../renderFullPage';
import { Router } from 'client/Router';
import { configureStore, runSaga } from 'client/store/configureStore';
```

I tried a lot in this sample, but still not work. Does anyone have any ideas about it?

**Comment by hiroppy** [comment]
Because `client/Router` doesn't exist in node_modules
