### ISSUE TITLE
Would you apply the latest version of 'loadable-components' to this project?

### ISSUE THREAD

**Issue by taruyar** [hiroppy/ssr-sample#175]
I'm struggling with the combination of SSR + Code Splitting + Redux Saga.
I appreciate and referred to a few part of your implementation.
Still, I don't know how latest version of loadable-components (https://github.com/smooth-code/loadable-components) can be combined with runSaga and other server related.
perhaps because I do not fully understand how loadable component works with runSaga.

tbh I would like to see your update if you will.

Pls close it if this is not the right place for asking.

**Comment by hiroppy** [comment]
I fixed this issue, thanks
